### ISSUE TITLE
Problems with time-varying parameters

### ISSUE THREAD

**Issue by VicencPuig** [do-mpc/do-mpc#92] opened 2020-12-03 16:51 UTC
**Describe the bug**
We have reproduced the example about TVP you have in the FAQs section but it appears an
error in line 38 when using defining: tvp_template = mpc.get_tvp_template().

See attached the implementation based on copying the exmple in the FAQs
[example_tvp.zip](https://github.com/do-mpc/do-mpc/files/5637585/example_tvp.zip)

Can you helping indicating which is the problem?

Thank you very much.

**Comment by 4flixt** [comment] 2020-12-03 19:20
Hi @VicencPuig,

thank you for your question. So first of all: The error is not on your side. There are two things here:

1. When I run your code I get the error: ``AssertionError: mterm must be solely a function of _x and _p.``.  Since you have:
```python
lterm = (model.x['temperature']-model.tvp['temperature_set_point'])**2
mterm = lterm
```
Your ``rterm`` is a function of ``tvp`` as well. However, this is not actually desirable as we realized ourselves not too long ago. In fact, this is already fixed on Github (main branch) but there is no release out yet with this change. I'll draft an intermediate release tomorrow. 

2. Even if I fix that piece of code by setting e.g. ``lterm=DM(0)``, your code will produce an error. This error is quite weird and due to Python [namespaces and scope](https://www.geeksforgeeks.org/namespaces-and-scope-in-python/).
Basically, your main script (``example_tvp.py``) is a namespace in which you define objects. When you pass these objects to do-mpc modules, actually you are passing the reference to that object in its namespace.  This creates a problem in your case because you have:

```python
# Get the proper template for time varying parameters.
tvp_template = mpc.get_tvp_template()


# Define the tvp function that allows to set the proper value to the time varying parameters in each MPC step.
def tvp_fun(t_now):
    for k in range(mpc.n_horizon):
        tvp_template['_tvp', k, 'temperature_set_point'] = 10
        tvp_template['_tvp', k, 'temperature_external'] = 20

    return tvp_template


mpc.set_tvp_fun(tvp_fun)
```

which creates the object ``tvp_template`` and passes its reference to the function ``tvp_fun`` which is then passed to the ``MPC`` class. All internal tests are passed, because everything is valid.

But now comes this block of code:

```python
tvp_template = simulator.get_tvp_template()


# Define the function (indexing is much simpler ...)
def tvp_fun(t_now):
        tvp_template['temperature_external'] = 20
        return tvp_template


# Set the tvp_fun:
simulator.set_tvp_fun(tvp_fun)

# Complete the simulator setup.
simulator.setup()
```

you get a **new** object ``tvp_template`` which is similar to the one above but not identical (it doesn't have multiple timesteps). This **new object with the same name** now **overwrites the old object in the same namespace**. Thus, when the ``MPC`` object tries to set elements on its ``tvp_template`` it will point to the wrong  ``tvp_template`` object and can't proceed. 

This example illustrates the issue:

```python
a = 2
def fun1():
    print('fun1 output:')
    print(a)


a = 3
def fun2():
    print('fun2 output:')
    print(a)


fun1()
fun2()
```
The return is:
```
fun1 output:
3
fun2 output:
3
``` 

The easy fix is to rename one of the ``tvp_templates`` and the take away is to not use the same name twice in the same scope if it can be avoided. 

Here is working copy of your supplied [example](https://github.com/do-mpc/do-mpc/files/5638443/example_tvp.py.zip).

Best,
4flixt

**Comment by 4flixt** [comment] 2020-12-04 09:54
Release [v4.1.1](https://github.com/do-mpc/do-mpc/releases/tag/v4.1.1) is now available. 
You can update from the terminal with

```
pip install do-mpc --upgrade
```

I also forgot to mention to other minor problems with your code from yesterday:

1. Please use ``x0=np.array([15])`` in this snippet instead of ``x0=15``.
```python
####### CONTROL LOOP #######
# Create the control loop.
x0 = 15
simulator.x0 = x0
mpc.x0 = x0
```

2. It is only possible to invoke:
```python
mpc_graphics.plot_predictions(t_ind=0)
```
if the MPC object has the additional setting:
```python
mpc.set_param(store_full_solution=True)
```

After fixing 1 and 2, as well as renaming the ``tvp_template`` for the simulator (see comment above) and the update to v4.1.1 your code will run as expected.

Best 
4flixt

**Comment by VicencPuig** [comment] 2020-12-04 10:15
Thank you very much for the fast reply and solution.



Best,



Vicenç



*De:* 4flixt [mailto:notifications@github.com]
*Enviado el:* viernes, 4 de diciembre de 2020 10:55
*Para:* do-mpc/do-mpc
*CC:* VicencPuig; Mention
*Asunto:* Re: [do-mpc/do-mpc] Problems with time-varying parameters (#92)



Release v4.1.1 <https://github.com/do-mpc/do-mpc/releases/tag/v4.1.1> is
now available.
You can update from the terminal with

pip install do-mpc --upgrade

I also forgot to mention to other minor problems with your code from
yesterday:

   1. Please use x0=np.array([15]) in this snippet instead of x0=15.

####### CONTROL LOOP #######

# Create the control loop.

x0 = 15

simulator.x0 = x0

mpc.x0 = x0


   1. It is only possible to invoke:

mpc_graphics.plot_predictions(t_ind=0)

if the MPC object has the additional setting:

mpc.set_param(store_full_solution=True)

After fixing 1 and 2, as well as renaming the tvp_template for the
simulator (see comment above) and the update to v4.1.1 your code will run
as expected.

Best
4flixt

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/do-mpc/do-mpc/issues/92#issuecomment-738688375>, or
unsubscribe

**Comment by HoussemCHAOUALI** [comment] 2020-12-07 10:04
Dear 4flixt,
Thank you for the explications you already gave us in this topic and the updated version. 
I reproduced the example you shared with Vicenc, and I am trying to change the "tvp_fun" function to generate an np.array output instead of a constant (20 as in your case), I get the following error :
 
raise Exception("Error occured in struct context with powerIndex %s, at canonicalIndex %s" % (str(powerIndex),str(canonicalIndex))) from e
Exception: Error occured in struct context with powerIndex ('temperature',), at canonicalIndex ()

Any help with this part please ? 


[TVP.zip](https://github.com/do-mpc/do-mpc/files/5651928/TVP.zip)

**Comment by 4flixt** [comment] 2020-12-07 11:07
Hi @HoussemCHAOUALI ,

thank you for question! The problem in your example is created, because you introduce the state of dimension 1 and the ``tvp`` of dimension 7:

```python
# Introduce state temperature:
temperature = model.set_variable(var_type='_x', var_name='temperature')
# Introduce tvp: Set-point for the temperature
temperature_set_point = model.set_variable(var_type='_tvp', var_name='temperature_set_point', shape=(7,1))
# Introduce tvp: External temperature (disturbance)
temperature_external = model.set_variable(var_type='_tvp', var_name='temperature_external',shape=(7,1))
```

and then you have:

```python
# Assume that the external temperature has an influence on our temperature state.
model.set_rhs('temperature', alpha*(temperature_external-temperature))
```

The difference in the expression above ```temperature_external-temperature``` works, even though you have different dimensions because of broadcasting. Thus you obtain a 7 dimensional vector. But do-mpc expects a one dimensional vector for the right hand side of the the one dimensional state ``temperature``. 

Unfortunately, you get a fairly meaningless error in that case. I'll add it to the list of improvements to catch this error and return a more meaningful message.

I fixed your code by increasing the state dimension to 7. I also had to adapt the ``lterm`` for the objective function (otherwise it wouldn't be a scalar). Here is the [file](https://github.com/do-mpc/do-mpc/files/5652244/TVP.py.zip).

Best
4flixt

**Comment by HoussemCHAOUALI** [comment] 2020-12-07 11:37
Thank you again for your fast reactivity, I will try to adapt my code based on your recommandations and modifications on the above example.
Also, I have a question regarding the RHS formulation. Being new to Github, I dont know yet if I have to create a new topic for this, or how can I contact you directly and privatly (if possible).

**Closed** 2021-01-11 08:45 UTC
Labels: Support
